using Bll.Inventory.StockTakking;
using Bll.MasterData.CompanyBll;
using Common.Utils;
using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using DTO.Inventory.StockTakking;
using Logger;
using Logger.Configuration;
using Logger.Interfaces;
using System;
using System.Threading.Tasks;

namespace Inventory.StockTakking
{
    public partial class FrmFrmStocktakingMasterAddEdit : XtraForm
    {
        #region ========== FIELDS & PROPERTIES ==========

        /// <summary>
        /// ID của StocktakingMaster (dùng khi edit)
        /// Guid.Empty nếu là thêm mới
        /// </summary>
        private readonly Guid _stocktakingMasterId;

        /// <summary>
        /// Business Logic Layer cho StocktakingMaster
        /// </summary>
        private readonly StocktakingMasterBll _stocktakingMasterBll = new StocktakingMasterBll();

        /// <summary>
        /// Business Logic Layer cho CompanyBranch (dùng cho Warehouse lookup)
        /// </summary>
        private readonly CompanyBranchBll _companyBranchBll = new CompanyBranchBll();

        /// <summary>
        /// Logger để ghi log
        /// </summary>
        private readonly ILogger _logger;

        /// <summary>
        /// Flag để kiểm tra xem số phiếu đã được tạo tự động chưa
        /// </summary>
        private bool _isVoucherNumberAutoGenerated;

        /// <summary>
        /// Giá trị số phiếu tự động tạo cuối cùng (để so sánh khi người dùng chỉnh sửa)
        /// </summary>
        private string _lastAutoGeneratedVoucherNumber = string.Empty;

        /// <summary>
        /// Flag để bỏ qua event EditValueChanged khi đang set giá trị tự động
        /// </summary>
        private bool _isSettingAutoValue;

        #endregion

        #region ========== CONSTRUCTOR ==========

        /// <summary>
        /// Constructor với tham số ID
        /// </summary>
        /// <param name="stocktakingMasterId">ID của StocktakingMaster. Guid.Empty nếu là thêm mới</param>
        public FrmFrmStocktakingMasterAddEdit(Guid stocktakingMasterId)
        {
            _stocktakingMasterId = stocktakingMasterId;
            _logger = LoggerFactory.CreateLogger(LogCategory.UI);
            InitializeComponent();
            InitializeForm();
        }

        #endregion

        #region ========== INITIALIZATION & SETUP ==========

        /// <summary>
        /// Khởi tạo form
        /// </summary>
        private void InitializeForm()
        {
            try
            {
                // Thiết lập Text của form theo ngữ cảnh
                SetFormTitle();

                // Load enum vào ComboBoxEdit (phải load trước khi load dữ liệu)
                LoadStocktakingTypeComboBox();
                LoadStocktakingStatusComboBox();

                // Xử lý theo chế độ (thêm mới hoặc điều chỉnh)
                if (_stocktakingMasterId == Guid.Empty)
                {
                    // Chế độ thêm mới
                    InitializeForAddMode();
                    
                    // Load datasource cho Warehouse (CompanyBranch) - có thể load async
                    _ = LoadWarehouseDataSourceAsync();
                }
                else
                {
                    // Chế độ điều chỉnh - LoadExistingData sẽ tự load datasource
                    InitializeForEditMode();
                }

                // Đăng ký event khi thay đổi ngày kiểm kho để tự động tạo lại số phiếu (chỉ khi thêm mới)
                StocktakingDateDateEdit.EditValueChanged += StocktakingDateDateEdit_EditValueChanged;
                
                // Đăng ký event khi người dùng chỉnh sửa số phiếu thủ công
                VoucherNumberTextEdit.EditValueChanged += VoucherNumberTextEdit_EditValueChanged;

                // Đăng ký event Popup cho WarehouseNameSearchLookupEdit để load lại dữ liệu khi mở popup
                WarehouseNameSearchLookupEdit.Popup += WarehouseNameSearchLookupEdit_Popup;

                // Đăng ký event handlers cho bar buttons
                SaveBarButtonItem.ItemClick += SaveBarButtonItem_ItemClick;
                CloseBarButtonItem.ItemClick += CloseBarButtonItem_ItemClick;

                // Setup SuperToolTips
                SetupSuperToolTips();
            }
            catch (Exception ex)
            {
                _logger.Error($"InitializeForm: Lỗi khởi tạo form: {ex.Message}", ex);
                ShowError(ex, "Lỗi khởi tạo form");
            }
        }

        /// <summary>
        /// Thiết lập Text của form theo ngữ cảnh (thêm mới hoặc điều chỉnh)
        /// </summary>
        private void SetFormTitle()
        {
            if (_stocktakingMasterId == Guid.Empty)
            {
                // Chế độ thêm mới
                Text = @"Thêm mới phiếu kiểm kho";
            }
            else
            {
                // Chế độ điều chỉnh
                Text = @"Điều chỉnh phiếu kiểm kho";
            }
        }

        /// <summary>
        /// Khởi tạo form cho chế độ thêm mới
        /// </summary>
        private void InitializeForAddMode()
        {
            try
            {
                _logger.Debug("InitializeForAddMode: Khởi tạo form cho chế độ thêm mới");

                // Thiết lập ngày kiểm kho mặc định là ngày hiện tại
                StocktakingDateDateEdit.DateTime = DateTime.Now;
                
                // Tự động tạo số phiếu khi thêm mới
                GenerateVoucherNumber();

                // Set mặc định cho các trường khác
                // Mặc định: Loại kiểm kho = Kiểm kho định kỳ, Trạng thái = Nháp
                SetStocktakingType(StocktakingTypeEnum.Periodic);
                SetStocktakingStatus(StocktakingStatusEnum.Draft);
            }
            catch (Exception ex)
            {
                _logger.Error($"InitializeForAddMode: Lỗi khởi tạo chế độ thêm mới: {ex.Message}", ex);
                throw;
            }
        }

        /// <summary>
        /// Khởi tạo form cho chế độ điều chỉnh
        /// </summary>
        private void InitializeForEditMode()
        {
            try
            {
                _logger.Debug($"InitializeForEditMode: Khởi tạo form cho chế độ điều chỉnh, Id={_stocktakingMasterId}");

                // Load dữ liệu từ database
                LoadExistingData();
            }
            catch (Exception ex)
            {
                _logger.Error($"InitializeForEditMode: Lỗi khởi tạo chế độ điều chỉnh: {ex.Message}", ex);
                throw;
            }
        }

        /// <summary>
        /// Xử lý khi thay đổi ngày kiểm kho
        /// Tự động tạo lại số phiếu nếu đang ở chế độ thêm mới và số phiếu chưa được chỉnh sửa thủ công
        /// </summary>
        private void StocktakingDateDateEdit_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                // Chỉ tự động tạo lại số phiếu nếu:
                // 1. Đang ở chế độ thêm mới
                // 2. Số phiếu đã được tạo tự động trước đó (chưa được chỉnh sửa thủ công)
                if (_stocktakingMasterId == Guid.Empty && _isVoucherNumberAutoGenerated)
                {
                    GenerateVoucherNumber();
                }
            }
            catch (Exception ex)
            {
                _logger.Error($"StocktakingDateDateEdit_EditValueChanged: Lỗi tạo số phiếu: {ex.Message}", ex);
                ShowError(ex, "Lỗi tạo số phiếu");
            }
        }

        /// <summary>
        /// Xử lý khi người dùng chỉnh sửa số phiếu thủ công
        /// Reset flag để không tự động tạo lại khi thay đổi ngày
        /// </summary>
        private void VoucherNumberTextEdit_EditValueChanged(object sender, EventArgs e)
        {
            // Bỏ qua event nếu đang set giá trị tự động
            if (_isSettingAutoValue)
                return;

            // Nếu người dùng chỉnh sửa số phiếu thủ công, đánh dấu là không còn tự động tạo nữa
            // Chỉ reset nếu đang ở chế độ thêm mới
            if (_stocktakingMasterId == Guid.Empty)
            {
                var currentVoucherNumber = VoucherNumberTextEdit.Text?.Trim();
                
                // Nếu giá trị hiện tại khác với giá trị tự động tạo cuối cùng
                // => Người dùng đã chỉnh sửa thủ công
                if (!string.IsNullOrEmpty(currentVoucherNumber) && 
                    currentVoucherNumber != _lastAutoGeneratedVoucherNumber)
                {
                    _isVoucherNumberAutoGenerated = false;
                }
            }
        }

        /// <summary>
        /// Tự động tạo số phiếu kiểm kho
        /// </summary>
        private void GenerateVoucherNumber()
        {
            try
            {
                // Chỉ tạo số phiếu khi đang thêm mới
                if (_stocktakingMasterId != Guid.Empty)
                    return;

                // Lấy ngày kiểm kho, nếu chưa có thì dùng ngày hiện tại
                var stocktakingDate = StocktakingDateDateEdit.DateTime;
                if (stocktakingDate == DateTime.MinValue)
                {
                    stocktakingDate = DateTime.Now;
                    StocktakingDateDateEdit.DateTime = stocktakingDate;
                }

                // Gọi BLL để tạo số phiếu
                var voucherNumber = _stocktakingMasterBll.GenerateVoucherNumber(stocktakingDate);
                
                // Set flag để bỏ qua event EditValueChanged
                _isSettingAutoValue = true;
                try
                {
                    // Gán số phiếu vào TextEdit
                    VoucherNumberTextEdit.Text = voucherNumber;
                    
                    // Lưu giá trị tự động tạo để so sánh sau này
                    _lastAutoGeneratedVoucherNumber = voucherNumber;
                    
                    // Đánh dấu đã tạo tự động
                    _isVoucherNumberAutoGenerated = true;
                }
                finally
                {
                    // Reset flag
                    _isSettingAutoValue = false;
                }
            }
            catch (Exception ex)
            {
                _logger.Error($"GenerateVoucherNumber: Lỗi tạo số phiếu tự động: {ex.Message}", ex);
                ShowError(ex, "Lỗi tạo số phiếu tự động");
            }
        }

        #endregion

        #region ========== ENUM HELPERS - STOCKTAKING TYPE ==========

        /// <summary>
        /// Load danh sách StocktakingTypeEnum vào ComboBoxEdit
        /// </summary>
        private void LoadStocktakingTypeComboBox()
        {
            try
            {
                StocktakingTypeComboBoxEdit.Properties.Items.Clear();

                // Load tất cả các giá trị enum với màu sắc HTML
                foreach (StocktakingTypeEnum value in Enum.GetValues(typeof(StocktakingTypeEnum)))
                {
                    int index = (int)value; // Sử dụng giá trị enum làm index (0, 1, 2, 3)
                    string description = ApplicationEnumUtils.GetDescription(value);
                    string colorHex = GetStocktakingTypeColor(value);

                    // Tạo HTML với màu sắc theo chuẩn DevExpress
                    string itemName = $"<color='{colorHex}'>{description}</color>";

                    // Insert vào ComboBox với index để sắp xếp đúng thứ tự
                    // Nếu index lớn hơn số items hiện tại, thêm vào cuối
                    if (index >= StocktakingTypeComboBoxEdit.Properties.Items.Count)
                    {
                        StocktakingTypeComboBoxEdit.Properties.Items.Add(itemName);
                    }
                    else
                    {
                        StocktakingTypeComboBoxEdit.Properties.Items.Insert(index, itemName);
                    }
                }

                // Cấu hình ComboBox
                StocktakingTypeComboBoxEdit.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
                StocktakingTypeComboBoxEdit.Properties.ShowDropDown = DevExpress.XtraEditors.Controls.ShowDropDown.SingleClick;

                // Sử dụng CustomDisplayText để hiển thị Description với màu sắc
                StocktakingTypeComboBoxEdit.Properties.CustomDisplayText += StocktakingTypeTextEdit_CustomDisplayText;
                
                // Đăng ký event khi chọn giá trị để convert sang enum
                StocktakingTypeComboBoxEdit.SelectedIndexChanged += StocktakingTypeTextEdit_SelectedIndexChanged;
            }
            catch (Exception ex)
            {
                _logger.Error($"LoadStocktakingTypeComboBox: Lỗi load danh sách loại kiểm kho: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Lấy màu sắc tương ứng với loại kiểm kho StocktakingTypeEnum
        /// </summary>
        /// <param name="stocktakingType">Loại kiểm kho</param>
        /// <returns>Tên màu (color name) theo chuẩn DevExpress</returns>
        private string GetStocktakingTypeColor(StocktakingTypeEnum stocktakingType)
        {
            return stocktakingType switch
            {
                StocktakingTypeEnum.Periodic => "blue",           // Blue - Kiểm kho định kỳ
                StocktakingTypeEnum.AdHoc => "orange",            // Orange - Kiểm kho đột xuất
                StocktakingTypeEnum.FullWarehouse => "green",     // Green - Kiểm kho toàn bộ kho
                StocktakingTypeEnum.ByProductList => "purple",    // Purple - Kiểm kho theo danh sách sản phẩm
                _ => "gray"                                       // Gray - Khác
            };
        }

        /// <summary>
        /// Event handler để hiển thị Description với màu sắc trong ComboBoxEdit
        /// </summary>
        private void StocktakingTypeTextEdit_CustomDisplayText(object sender, DevExpress.XtraEditors.Controls.CustomDisplayTextEventArgs e)
        {
            try
            {
                if (e.Value == null) return;

                StocktakingTypeEnum stocktakingTypeValue;

                // Nếu giá trị là string (Description với HTML), convert về enum
                if (e.Value is string stringValue)
                {
                    var stocktakingTypeEnum = GetStocktakingTypeEnumFromDescription(stringValue);
                    if (!stocktakingTypeEnum.HasValue)
                    {
                        e.DisplayText = stringValue; // Giữ nguyên nếu không convert được
                        return;
                    }
                    stocktakingTypeValue = stocktakingTypeEnum.Value;
                }
                else if (e.Value is StocktakingTypeEnum enumValue)
                {
                    stocktakingTypeValue = enumValue;
                }
                else if (e.Value is int intValue && Enum.IsDefined(typeof(StocktakingTypeEnum), intValue))
                {
                    stocktakingTypeValue = (StocktakingTypeEnum)intValue;
                }
                else
                {
                    return;
                }

                // Lấy Description và màu sắc
                var description = ApplicationEnumUtils.GetDescription(stocktakingTypeValue);
                var colorHex = GetStocktakingTypeColor(stocktakingTypeValue);

                // Tạo HTML với màu sắc theo chuẩn DevExpress
                e.DisplayText = $"<color='{colorHex}'>{description}</color>";
            }
            catch (Exception ex)
            {
                _logger.Error($"StocktakingTypeTextEdit_CustomDisplayText: Lỗi hiển thị loại kiểm kho: {ex.Message}", ex);
                // Nếu có lỗi, hiển thị giá trị mặc định
                e.DisplayText = e.Value?.ToString() ?? string.Empty;
            }
        }

        /// <summary>
        /// Xử lý khi chọn giá trị từ ComboBox
        /// Convert SelectedIndex thành enum và lưu vào Tag để có thể lấy lại sau
        /// </summary>
        private void StocktakingTypeTextEdit_SelectedIndexChanged(object sender, EventArgs e)
        {
            try
            {
                var comboBoxEdit = sender as ComboBoxEdit;
                if (comboBoxEdit == null) return;

                var selectedIndex = comboBoxEdit.SelectedIndex;
                if (selectedIndex >= 0 && selectedIndex < comboBoxEdit.Properties.Items.Count)
                {
                    // Convert index thành enum
                    if (Enum.IsDefined(typeof(StocktakingTypeEnum), selectedIndex))
                    {
                        var enumValue = (StocktakingTypeEnum)selectedIndex;
                        // Lưu enum value vào Tag để có thể lấy lại sau
                        comboBoxEdit.Tag = enumValue;
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.Error($"StocktakingTypeTextEdit_SelectedIndexChanged: Lỗi xử lý thay đổi loại kiểm kho: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Lấy giá trị enum hiện tại từ ComboBox
        /// </summary>
        /// <returns>StocktakingTypeEnum hoặc null</returns>
        private StocktakingTypeEnum? GetSelectedStocktakingType()
        {
            try
            {
                var selectedIndex = StocktakingTypeComboBoxEdit.SelectedIndex;
                if (selectedIndex >= 0 && Enum.IsDefined(typeof(StocktakingTypeEnum), selectedIndex))
                {
                    return (StocktakingTypeEnum)selectedIndex;
                }

                // Fallback: Lấy từ Tag nếu có
                if (StocktakingTypeComboBoxEdit.Tag is StocktakingTypeEnum enumValue)
                {
                    return enumValue;
                }

                return null;
            }
            catch
            {
                return null;
            }
        }

        /// <summary>
        /// Set giá trị enum vào ComboBox
        /// </summary>
        /// <param name="stocktakingType">Giá trị enum cần set</param>
        private void SetStocktakingType(StocktakingTypeEnum stocktakingType)
        {
            try
            {
                var index = (int)stocktakingType;
                if (index >= 0 && index < StocktakingTypeComboBoxEdit.Properties.Items.Count)
                {
                    StocktakingTypeComboBoxEdit.SelectedIndex = index;
                    StocktakingTypeComboBoxEdit.Tag = stocktakingType;
                }
            }
            catch (Exception ex)
            {
                _logger.Error($"SetStocktakingType: Lỗi set loại kiểm kho: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Set giá trị enum vào ComboBox Status
        /// </summary>
        /// <param name="stocktakingStatus">Giá trị enum cần set</param>
        private void SetStocktakingStatus(StocktakingStatusEnum stocktakingStatus)
        {
            try
            {
                var index = (int)stocktakingStatus;
                if (index >= 0 && index < StocktakingStatusComboBoxEdit.Properties.Items.Count)
                {
                    StocktakingStatusComboBoxEdit.SelectedIndex = index;
                    StocktakingStatusComboBoxEdit.Tag = stocktakingStatus;
                }
            }
            catch (Exception ex)
            {
                _logger.Error($"SetStocktakingStatus: Lỗi set trạng thái kiểm kho: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Lấy enum từ description (loại bỏ HTML tags)
        /// </summary>
        private StocktakingTypeEnum? GetStocktakingTypeEnumFromDescription(string description)
        {
            if (string.IsNullOrWhiteSpace(description))
                return null;

            // Loại bỏ HTML tags nếu có
            var cleanDescription = description;
            if (description.Contains("<color"))
            {
                // Extract text từ HTML: <color='xxx'>Text</color>
                var startIndex = description.IndexOf('>') + 1;
                var endIndex = description.LastIndexOf('<');
                if (startIndex > 0 && endIndex > startIndex)
                {
                    cleanDescription = description.Substring(startIndex, endIndex - startIndex);
                }
            }

            // Tìm enum value từ description
            foreach (StocktakingTypeEnum value in Enum.GetValues(typeof(StocktakingTypeEnum)))
            {
                var enumDescription = ApplicationEnumUtils.GetDescription(value);
                if (string.Equals(enumDescription, cleanDescription, StringComparison.OrdinalIgnoreCase))
                {
                    return value;
                }
            }

            return null;
        }

        #endregion

        #region ========== ENUM HELPERS - STOCKTAKING STATUS ==========

        /// <summary>
        /// Load danh sách StocktakingStatusEnum vào ComboBoxEdit
        /// </summary>
        private void LoadStocktakingStatusComboBox()
        {
            try
            {
                StocktakingStatusComboBoxEdit.Properties.Items.Clear();

                // Load tất cả các giá trị enum với màu sắc HTML
                foreach (StocktakingStatusEnum value in Enum.GetValues(typeof(StocktakingStatusEnum)))
                {
                    int index = (int)value; // Sử dụng giá trị enum làm index (0, 1, 2, 3, 4)
                    string description = ApplicationEnumUtils.GetDescription(value);
                    string colorHex = GetStocktakingStatusColor(value);

                    // Tạo HTML với màu sắc theo chuẩn DevExpress
                    string itemName = $"<color='{colorHex}'>{description}</color>";

                    // Insert vào ComboBox với index để sắp xếp đúng thứ tự
                    // Nếu index lớn hơn số items hiện tại, thêm vào cuối
                    if (index >= StocktakingStatusComboBoxEdit.Properties.Items.Count)
                    {
                        StocktakingStatusComboBoxEdit.Properties.Items.Add(itemName);
                    }
                    else
                    {
                        StocktakingStatusComboBoxEdit.Properties.Items.Insert(index, itemName);
                    }
                }

                // Cấu hình ComboBox (CheckedComboBoxEdit có thể dùng như ComboBoxEdit khi chỉ chọn 1 giá trị)
                StocktakingStatusComboBoxEdit.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
                StocktakingStatusComboBoxEdit.Properties.ShowDropDown = DevExpress.XtraEditors.Controls.ShowDropDown.SingleClick;

                // Sử dụng CustomDisplayText để hiển thị Description với màu sắc
                StocktakingStatusComboBoxEdit.Properties.CustomDisplayText += StocktakingStatusComboBoxEdit_CustomDisplayText;
                
                // Đăng ký event khi chọn giá trị để convert sang enum
                StocktakingStatusComboBoxEdit.SelectedIndexChanged += StocktakingStatusComboBoxEdit_SelectedIndexChanged;
            }
            catch (Exception ex)
            {
                _logger.Error($"LoadStocktakingStatusComboBox: Lỗi load danh sách trạng thái kiểm kho: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Lấy màu sắc tương ứng với trạng thái kiểm kho StocktakingStatusEnum
        /// </summary>
        /// <param name="stocktakingStatus">Trạng thái kiểm kho</param>
        /// <returns>Tên màu (color name) theo chuẩn DevExpress</returns>
        private string GetStocktakingStatusColor(StocktakingStatusEnum stocktakingStatus)
        {
            return stocktakingStatus switch
            {
                StocktakingStatusEnum.Draft => "gray",           // Gray - Nháp
                StocktakingStatusEnum.InProgress => "blue",      // Blue - Đang kiểm
                StocktakingStatusEnum.Completed => "green",     // Green - Hoàn thành
                StocktakingStatusEnum.Approved => "darkgreen",  // Dark Green - Đã duyệt
                StocktakingStatusEnum.Cancelled => "red",       // Red - Đã hủy
                _ => "gray"                                      // Gray - Khác
            };
        }

        /// <summary>
        /// Event handler để hiển thị Description với màu sắc trong ComboBoxEdit
        /// </summary>
        private void StocktakingStatusComboBoxEdit_CustomDisplayText(object sender, DevExpress.XtraEditors.Controls.CustomDisplayTextEventArgs e)
        {
            try
            {
                if (e.Value == null) return;

                StocktakingStatusEnum stocktakingStatusValue;

                // Nếu giá trị là string (Description với HTML), convert về enum
                if (e.Value is string stringValue)
                {
                    var stocktakingStatusEnum = GetStocktakingStatusEnumFromDescription(stringValue);
                    if (!stocktakingStatusEnum.HasValue)
                    {
                        e.DisplayText = stringValue; // Giữ nguyên nếu không convert được
                        return;
                    }
                    stocktakingStatusValue = stocktakingStatusEnum.Value;
                }
                else if (e.Value is StocktakingStatusEnum enumValue)
                {
                    stocktakingStatusValue = enumValue;
                }
                else if (e.Value is int intValue && Enum.IsDefined(typeof(StocktakingStatusEnum), intValue))
                {
                    stocktakingStatusValue = (StocktakingStatusEnum)intValue;
                }
                else
                {
                    return;
                }

                // Lấy Description và màu sắc
                var description = ApplicationEnumUtils.GetDescription(stocktakingStatusValue);
                var colorHex = GetStocktakingStatusColor(stocktakingStatusValue);

                // Tạo HTML với màu sắc theo chuẩn DevExpress
                e.DisplayText = $"<color='{colorHex}'>{description}</color>";
            }
            catch (Exception ex)
            {
                _logger.Error($"StocktakingStatusComboBoxEdit_CustomDisplayText: Lỗi hiển thị trạng thái kiểm kho: {ex.Message}", ex);
                // Nếu có lỗi, hiển thị giá trị mặc định
                e.DisplayText = e.Value?.ToString() ?? string.Empty;
            }
        }

        /// <summary>
        /// Xử lý khi chọn giá trị từ ComboBox
        /// Convert SelectedIndex thành enum và lưu vào Tag để có thể lấy lại sau
        /// </summary>
        private void StocktakingStatusComboBoxEdit_SelectedIndexChanged(object sender, EventArgs e)
        {
            try
            {
                var comboBoxEdit = sender as ComboBoxEdit;
                if (comboBoxEdit == null) return;

                var selectedIndex = comboBoxEdit.SelectedIndex;
                if (selectedIndex >= 0 && selectedIndex < comboBoxEdit.Properties.Items.Count)
                {
                    // Convert index thành enum
                    if (Enum.IsDefined(typeof(StocktakingStatusEnum), selectedIndex))
                    {
                        var enumValue = (StocktakingStatusEnum)selectedIndex;
                        // Lưu enum value vào Tag để có thể lấy lại sau
                        comboBoxEdit.Tag = enumValue;
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.Error($"StocktakingStatusComboBoxEdit_SelectedIndexChanged: Lỗi xử lý thay đổi trạng thái kiểm kho: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Lấy enum từ description (loại bỏ HTML tags)
        /// </summary>
        private StocktakingStatusEnum? GetStocktakingStatusEnumFromDescription(string description)
        {
            if (string.IsNullOrWhiteSpace(description))
                return null;

            // Loại bỏ HTML tags nếu có
            var cleanDescription = description;
            if (description.Contains("<color"))
            {
                // Extract text từ HTML: <color='xxx'>Text</color>
                var startIndex = description.IndexOf('>') + 1;
                var endIndex = description.LastIndexOf('<');
                if (startIndex > 0 && endIndex > startIndex)
                {
                    cleanDescription = description.Substring(startIndex, endIndex - startIndex);
                }
            }

            // Tìm enum value từ description
            foreach (StocktakingStatusEnum value in Enum.GetValues(typeof(StocktakingStatusEnum)))
            {
                var enumDescription = ApplicationEnumUtils.GetDescription(value);
                if (string.Equals(enumDescription, cleanDescription, StringComparison.OrdinalIgnoreCase))
                {
                    return value;
                }
            }

            return null;
        }

        /// <summary>
        /// Lấy giá trị enum hiện tại từ ComboBox Status
        /// </summary>
        /// <returns>StocktakingStatusEnum hoặc null</returns>
        private StocktakingStatusEnum? GetSelectedStocktakingStatus()
        {
            try
            {
                var selectedIndex = StocktakingStatusComboBoxEdit.SelectedIndex;
                if (selectedIndex >= 0 && Enum.IsDefined(typeof(StocktakingStatusEnum), selectedIndex))
                {
                    return (StocktakingStatusEnum)selectedIndex;
                }

                // Fallback: Lấy từ Tag nếu có
                if (StocktakingStatusComboBoxEdit.Tag is StocktakingStatusEnum enumValue)
                {
                    return enumValue;
                }

                return null;
            }
            catch
            {
                return null;
            }
        }

        #endregion

        #region ========== DATA LOADING ==========

        /// <summary>
        /// Load dữ liệu từ database khi ở chế độ điều chỉnh
        /// </summary>
        private async void LoadExistingData()
        {
            try
            {
                _logger.Debug($"LoadExistingData: Bắt đầu load dữ liệu, Id={_stocktakingMasterId}");

                // Đảm bảo datasource đã được load trước
                await LoadWarehouseDataSourceAsync();

                // Lấy DTO từ BLL
                var dto = _stocktakingMasterBll.GetById(_stocktakingMasterId);
                if (dto == null)
                {
                    throw new InvalidOperationException($"Không tìm thấy phiếu kiểm kho với ID: {_stocktakingMasterId}");
                }

                _logger.Info($"LoadExistingData: Đã load dữ liệu thành công, VoucherNumber={dto.VoucherNumber}");

                // Load dữ liệu vào các controls
                // Thông tin cơ bản
                StocktakingDateDateEdit.DateTime = dto.StocktakingDate;
                VoucherNumberTextEdit.Text = dto.VoucherNumber;
                
                // Set enum values
                SetStocktakingType(dto.StocktakingType);
                SetStocktakingStatus(dto.StocktakingStatus);

                // Kho kiểm - set sau khi datasource đã load
                WarehouseNameSearchLookupEdit.EditValue = dto.WarehouseId;

                // Thời gian kiểm kho
                if (dto.StartDate.HasValue)
                    StartDateDateEdit.EditValue = dto.StartDate.Value;
                if (dto.EndDate.HasValue)
                    EndDateDateEdit.EditValue = dto.EndDate.Value;

                // Quy trình phê duyệt
                if (dto.CountedDate.HasValue)
                    CountedDateDateEdit.EditValue = dto.CountedDate.Value;
                if (dto.ReviewedDate.HasValue)
                    ReviewedDateDateEdit.EditValue = dto.ReviewedDate.Value;
                if (dto.ApprovedDate.HasValue)
                    ApprovedDateDateEdit.EditValue = dto.ApprovedDate.Value;

                // Thông tin bổ sung
                NotesTextEdit.Text = dto.Notes ?? string.Empty;
                ReasonTextEdit.Text = dto.Reason ?? string.Empty;

                // Khóa phiếu
                IsLockedToggleSwitch.EditValue = dto.IsLocked;

                // Disable số phiếu nếu đã lưu (không cho phép chỉnh sửa)
                if (!string.IsNullOrEmpty(dto.VoucherNumber))
                {
                    VoucherNumberTextEdit.Properties.ReadOnly = true;
                    _isVoucherNumberAutoGenerated = false; // Không tự động tạo lại khi edit
                }
            }
            catch (Exception ex)
            {
                _logger.Error($"LoadExistingData: Lỗi load dữ liệu: {ex.Message}", ex);
                ShowError(ex, "Lỗi tải dữ liệu phiếu kiểm kho");
                throw;
            }
        }

        /// <summary>
        /// Load datasource cho Warehouse (CompanyBranch) - Load toàn bộ danh sách
        /// </summary>
        private async Task LoadWarehouseDataSourceAsync()
        {
            try
            {
                companyBranchDtoBindingSource.DataSource = await Task.Run(() => _companyBranchBll.GetAll());
            }
            catch (Exception ex)
            {
                _logger.Error($"LoadWarehouseDataSourceAsync: Lỗi tải dữ liệu kho: {ex.Message}", ex);
                ShowError(ex, "Lỗi tải dữ liệu kho");
            }
        }

        /// <summary>
        /// Xử lý khi mở popup của WarehouseNameSearchLookupEdit
        /// Load lại dữ liệu để đảm bảo có dữ liệu mới nhất
        /// </summary>
        private async void WarehouseNameSearchLookupEdit_Popup(object sender, EventArgs e)
        {
            try
            {
                await LoadWarehouseDataSourceAsync();
            }
            catch (Exception ex)
            {
                _logger.Error($"WarehouseNameSearchLookupEdit_Popup: Lỗi tải dữ liệu kho: {ex.Message}", ex);
                ShowError(ex, "Lỗi tải dữ liệu kho");
            }
        }

        #endregion

        #region ========== EVENT HANDLERS ==========

        /// <summary>
        /// Xử lý khi click nút Lưu
        /// </summary>
        private async void SaveBarButtonItem_ItemClick(object sender, ItemClickEventArgs e)
        {
            try
            {
                _logger.Debug("SaveBarButtonItem_ItemClick: Bắt đầu lưu phiếu kiểm kho");

                // Validate dữ liệu trước khi lưu
                if (!ValidateInput())
                {
                    _logger.Warning("SaveBarButtonItem_ItemClick: Validation thất bại");
                    return;
                }

                // Lấy DTO từ form
                var dto = GetDto();
                if (dto == null)
                {
                    _logger.Warning("SaveBarButtonItem_ItemClick: Không thể lấy DTO từ form");
                    ShowError("Không thể lấy dữ liệu từ form. Vui lòng kiểm tra lại.");
                    return;
                }

                // Lưu vào database
                var savedDto = await Task.Run(() => _stocktakingMasterBll.SaveOrUpdate(dto));
                
                if (savedDto != null)
                {
                    _logger.Info($"SaveBarButtonItem_ItemClick: Lưu phiếu kiểm kho thành công, Id={savedDto.Id}, VoucherNumber={savedDto.VoucherNumber}");
                    
                    // Hiển thị thông báo thành công
                    var parentForm = FindForm();
                    MsgBox.ShowSuccess("Lưu phiếu kiểm kho thành công!", "Thành công", parentForm);
                    
                    // Đóng form và trả về DialogResult.OK
                    DialogResult = System.Windows.Forms.DialogResult.OK;
                    Close();
                }
                else
                {
                    _logger.Warning("SaveBarButtonItem_ItemClick: Lưu phiếu kiểm kho thất bại - savedDto is null");
                    ShowError("Lưu phiếu kiểm kho thất bại. Vui lòng thử lại.");
                }
            }
            catch (Exception ex)
            {
                _logger.Error($"SaveBarButtonItem_ItemClick: Lỗi lưu phiếu kiểm kho: {ex.Message}", ex);
                ShowError(ex, "Lỗi lưu phiếu kiểm kho");
            }
        }

        /// <summary>
        /// Xử lý khi click nút Đóng
        /// </summary>
        private void CloseBarButtonItem_ItemClick(object sender, ItemClickEventArgs e)
        {
            try
            {
                _logger.Debug("CloseBarButtonItem_ItemClick: Đóng form");
                
                // Đóng form và trả về DialogResult.Cancel
                DialogResult = System.Windows.Forms.DialogResult.Cancel;
                Close();
            }
            catch (Exception ex)
            {
                _logger.Error($"CloseBarButtonItem_ItemClick: Lỗi đóng form: {ex.Message}", ex);
                ShowError(ex, "Lỗi đóng form");
            }
        }

        #endregion

        #region ========== VALIDATION ==========

        /// <summary>
        /// Validate dữ liệu input và hiển thị lỗi bằng dxErrorProvider
        /// </summary>
        private bool ValidateInput()
        {
            try
            {
                dxErrorProvider1.ClearErrors();

                // Ngày kiểm kho không được để trống
                if (StocktakingDateDateEdit.EditValue is null)
                {
                    dxErrorProvider1.SetError(StocktakingDateDateEdit, "Ngày kiểm kho không được để trống");
                    return false;
                }

                // Số phiếu không được để trống
                if (string.IsNullOrWhiteSpace(VoucherNumberTextEdit.Text))
                {
                    dxErrorProvider1.SetError(VoucherNumberTextEdit, "Số phiếu kiểm kho không được để trống");
                    return false;
                }

                // Kiểm tra độ dài số phiếu (tối đa 50 ký tự)
                if (VoucherNumberTextEdit.Text.Length > 50)
                {
                    dxErrorProvider1.SetError(VoucherNumberTextEdit, "Số phiếu kiểm kho không được vượt quá 50 ký tự");
                    return false;
                }

                // Loại kiểm kho phải được chọn
                var selectedType = GetSelectedStocktakingType();
                if (!selectedType.HasValue)
                {
                    dxErrorProvider1.SetError(StocktakingTypeComboBoxEdit, "Loại kiểm kho không được để trống");
                    return false;
                }

                // Trạng thái kiểm kho phải được chọn
                var selectedStatus = GetSelectedStocktakingStatus();
                if (!selectedStatus.HasValue)
                {
                    dxErrorProvider1.SetError(StocktakingStatusComboBoxEdit, "Trạng thái kiểm kho không được để trống");
                    return false;
                }

                // Kho kiểm không được để trống
                if (WarehouseNameSearchLookupEdit.EditValue is not Guid warehouseId || warehouseId == Guid.Empty)
                {
                    dxErrorProvider1.SetError(WarehouseNameSearchLookupEdit, "Kho kiểm không được để trống");
                    return false;
                }

                return true;
            }
            catch (Exception ex)
            {
                _logger.Error($"ValidateInput: Lỗi validate dữ liệu: {ex.Message}", ex);
                ShowError(ex, "Lỗi validate dữ liệu");
                return false;
            }
        }

        #endregion

        #region ========== DATA CONVERSION ==========

        /// <summary>
        /// Lấy DTO từ các control sau khi validate các trường bắt buộc
        /// </summary>
        /// <returns>StocktakingMasterDto nếu validation thành công, null nếu có lỗi</returns>
        private StocktakingMasterDto GetDto()
        {
            try
            {
                // Validate các trường bắt buộc
                if (!ValidateInput())
                {
                    return null; // Validation thất bại
                }

                // Lấy các giá trị từ controls
                var stocktakingDate = StocktakingDateDateEdit.DateTime;
                var voucherNumber = VoucherNumberTextEdit.Text?.Trim() ?? string.Empty;
                var selectedType = GetSelectedStocktakingType();
                var selectedStatus = GetSelectedStocktakingStatus();
                var warehouseId = WarehouseNameSearchLookupEdit.EditValue is Guid wId ? wId : Guid.Empty;

                // Kiểm tra các giá trị bắt buộc
                if (stocktakingDate == DateTime.MinValue || !selectedType.HasValue || !selectedStatus.HasValue || warehouseId == Guid.Empty)
                {
                    return null;
                }

                // Tạo DTO
                var dto = new StocktakingMasterDto
                {
                    // Thông tin cơ bản
                    Id = _stocktakingMasterId,
                    StocktakingDate = stocktakingDate,
                    VoucherNumber = voucherNumber,
                    StocktakingType = selectedType.Value,
                    StocktakingStatus = selectedStatus.Value,
                    WarehouseId = warehouseId,
                    CompanyBranchId = warehouseId, // CompanyBranchId = WarehouseId (vì warehouse là company branch)

                    // Thời gian kiểm kho
                    StartDate = StartDateDateEdit.EditValue is DateTime startDate ? startDate : null,
                    EndDate = EndDateDateEdit.EditValue is DateTime endDate ? endDate : null,

                    // Quy trình phê duyệt
                    CountedDate = CountedDateDateEdit.EditValue is DateTime countedDate ? countedDate : null,
                    ReviewedDate = ReviewedDateDateEdit.EditValue is DateTime reviewedDate ? reviewedDate : null,
                    ApprovedDate = ApprovedDateDateEdit.EditValue is DateTime approvedDate ? approvedDate : null,

                    // Thông tin bổ sung
                    Notes = NotesTextEdit.Text?.Trim() ?? string.Empty,
                    Reason = ReasonTextEdit.Text?.Trim() ?? string.Empty,

                    // Khóa phiếu
                    IsLocked = IsLockedToggleSwitch.EditValue is bool isLocked && isLocked,
                    LockedDate = IsLockedToggleSwitch.EditValue is bool locked && locked ? DateTime.Now : null,

                    // Trạng thái
                    IsActive = true,
                    IsDeleted = false,

                    // Audit fields
                    CreatedDate = _stocktakingMasterId == Guid.Empty ? DateTime.Now : null,
                    UpdatedDate = DateTime.Now
                };

                return dto;
            }
            catch (Exception ex)
            {
                _logger.Error($"GetDto: Lỗi lấy dữ liệu từ form: {ex.Message}", ex);
                ShowError(ex, "Lỗi lấy dữ liệu");
                return null;
            }
        }

        #endregion

        #region ========== SUPERTOOLTIP ==========

        /// <summary>
        /// Thiết lập SuperToolTip cho tất cả các controls trong form
        /// </summary>
        private void SetupSuperToolTips()
        {
            try
            {
                SetupBarButtonSuperTips();
                SetupTextEditSuperTips();
                SetupDateEditSuperTips();
                SetupComboBoxEditSuperTips();
                SetupSearchLookupEditSuperTips();
                SetupMemoEditSuperTips();
                SetupToggleSwitchSuperTips();
            }
            catch (Exception ex)
            {
                _logger.Error($"SetupSuperToolTips: Lỗi thiết lập SuperToolTip: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Thiết lập SuperToolTip cho các BarButton controls
        /// </summary>
        private void SetupBarButtonSuperTips()
        {
            // SuperTip cho nút Lưu
            if (SaveBarButtonItem != null)
            {
                SuperToolTipHelper.SetBarButtonSuperTip(
                    SaveBarButtonItem,
                    title: @"<b><color=Green>💾 Lưu</color></b>",
                    content: @"Lưu phiếu kiểm kho vào database.<br/><br/><b>Chức năng:</b><br/>• Validate dữ liệu trước khi lưu<br/>• Lưu thông tin phiếu kiểm kho vào database<br/>• Đóng form sau khi lưu thành công<br/><br/><b>Quy trình:</b><br/>1. Validate các trường bắt buộc<br/>2. Lấy dữ liệu từ form<br/>3. Gọi BLL.SaveOrUpdate() để lưu<br/>4. Hiển thị thông báo thành công<br/>5. Đóng form<br/><br/><b>Validation:</b><br/>• Ngày kiểm kho không được để trống<br/>• Số phiếu không được để trống (tối đa 50 ký tự)<br/>• Loại kiểm kho phải được chọn<br/>• Trạng thái kiểm kho phải được chọn<br/>• Kho kiểm không được để trống<br/><br/><color=Gray>Lưu ý:</color> Hệ thống sẽ tự động tạo số phiếu nếu chưa có."
                );
            }

            // SuperTip cho nút Đóng
            if (CloseBarButtonItem != null)
            {
                SuperToolTipHelper.SetBarButtonSuperTip(
                    CloseBarButtonItem,
                    title: @"<b><color=Red>❌ Đóng</color></b>",
                    content: @"Đóng form và không lưu dữ liệu.<br/><br/><b>Chức năng:</b><br/>• Đóng form hiện tại<br/>• Không lưu dữ liệu vào database<br/>• Hủy bỏ mọi thay đổi chưa lưu<br/><br/><color=Gray>Lưu ý:</color> Nếu bạn đã chỉnh sửa phiếu kiểm kho, hãy nhớ click <b>Lưu</b> trước khi đóng form."
                );
            }
        }

        /// <summary>
        /// Thiết lập SuperToolTip cho các TextEdit controls
        /// </summary>
        private void SetupTextEditSuperTips()
        {
            // SuperTip cho Số phiếu kiểm kho
            if (VoucherNumberTextEdit != null)
            {
                SuperToolTipHelper.SetTextEditSuperTip(
                    VoucherNumberTextEdit,
                    title: @"<b><color=DarkBlue>📄 Số phiếu kiểm kho</color></b>",
                    content: @"Số phiếu kiểm kho được tạo tự động theo format: <b>KK-YYYY-XXX</b><br/><br/><b>Format:</b><br/>• KK: Kiểm kho<br/>• YYYY: Năm (4 ký tự)<br/>• XXX: Số thứ tự phiếu (3 ký tự từ 001 đến 999)<br/><br/><b>Chức năng:</b><br/>• Tự động tạo khi thay đổi ngày kiểm kho<br/>• Query database để lấy số thứ tự tiếp theo<br/>• Đảm bảo số phiếu duy nhất trong cùng năm<br/><br/><b>Ràng buộc:</b><br/>• <b><color=Red>Bắt buộc nhập</color></b> (có dấu * đỏ)<br/>• Không được để trống<br/>• Tối đa 50 ký tự<br/><br/><b>Validation:</b><br/>• Kiểm tra rỗng khi validating<br/>• Hiển thị lỗi: ""Số phiếu kiểm kho không được để trống""<br/>• Hiển thị lỗi qua ErrorProvider nếu không hợp lệ<br/><br/><color=Gray>Lưu ý:</color> Số phiếu kiểm kho sẽ được lưu vào database khi lưu phiếu kiểm kho."
                );
            }
        }

        /// <summary>
        /// Thiết lập SuperToolTip cho các DateEdit controls
        /// </summary>
        private void SetupDateEditSuperTips()
        {
            // SuperTip cho Ngày kiểm kho
            if (StocktakingDateDateEdit != null)
            {
                SuperToolTipHelper.SetBaseEditSuperTip(
                    StocktakingDateDateEdit,
                    title: @"<b><color=DarkBlue>📅 Ngày kiểm kho</color></b>",
                    content: @"Chọn ngày kiểm kho cho phiếu kiểm.<br/><br/><b>Chức năng:</b><br/>• Xác định thời điểm kiểm kho<br/>• Tự động tạo số phiếu kiểm kho dựa trên ngày<br/>• Format số phiếu: KK-YYYY-XXX (YYYY từ ngày này)<br/>• Query database để lấy số thứ tự tiếp theo trong năm<br/><br/><b>Ràng buộc:</b><br/>• <b><color=Red>Bắt buộc nhập</color></b> (có dấu * đỏ)<br/>• Không được để trống<br/>• Mặc định: Ngày hiện tại<br/><br/><b>Validation:</b><br/>• Kiểm tra rỗng khi validating<br/>• Hiển thị lỗi: ""Ngày kiểm kho không được để trống""<br/>• Hiển thị lỗi qua ErrorProvider nếu không hợp lệ<br/><br/><color=Gray>Lưu ý:</color> Khi thay đổi ngày kiểm kho, hệ thống sẽ tự động tạo lại số phiếu kiểm kho theo format mới."
                );
            }
        }

        /// <summary>
        /// Thiết lập SuperToolTip cho các ComboBoxEdit controls
        /// </summary>
        private void SetupComboBoxEditSuperTips()
        {
            // SuperTip cho Loại kiểm kho
            if (StocktakingTypeComboBoxEdit != null)
            {
                SuperToolTipHelper.SetBaseEditSuperTip(
                    StocktakingTypeComboBoxEdit,
                    title: @"<b><color=DarkBlue>📋 Loại kiểm kho</color></b>",
                    content: @"Chọn loại kiểm kho từ danh sách.<br/><br/><b>Các loại kiểm kho:</b><br/>• <color=Blue>Kiểm kho định kỳ</color>: Kiểm kho theo lịch định kỳ<br/>• <color=Orange>Kiểm kho đột xuất</color>: Kiểm kho không theo lịch<br/>• <color=Green>Kiểm kho toàn bộ kho</color>: Kiểm toàn bộ sản phẩm trong kho<br/>• <color=Purple>Kiểm kho theo danh sách sản phẩm</color>: Kiểm theo danh sách cụ thể<br/><br/><b>Ràng buộc:</b><br/>• <b><color=Red>Bắt buộc chọn</color></b> (có dấu * đỏ)<br/>• Không được để trống<br/><br/><b>Validation:</b><br/>• Kiểm tra rỗng khi validating<br/>• Hiển thị lỗi: ""Loại kiểm kho không được để trống""<br/><br/><color=Gray>Lưu ý:</color> Loại kiểm kho sẽ được lưu vào database khi lưu phiếu kiểm kho."
                );
            }

            // SuperTip cho Trạng thái kiểm kho
            if (StocktakingStatusComboBoxEdit != null)
            {
                SuperToolTipHelper.SetBaseEditSuperTip(
                    StocktakingStatusComboBoxEdit,
                    title: @"<b><color=DarkBlue>📊 Trạng thái kiểm kho</color></b>",
                    content: @"Chọn trạng thái kiểm kho từ danh sách.<br/><br/><b>Các trạng thái:</b><br/>• <color=Gray>Nháp</color>: Phiếu mới tạo, chưa bắt đầu kiểm<br/>• <color=Blue>Đang kiểm</color>: Đang trong quá trình kiểm kho<br/>• <color=Green>Hoàn thành</color>: Đã hoàn thành kiểm kho<br/>• <color=DarkGreen>Đã duyệt</color>: Đã được duyệt và xác nhận<br/>• <color=Red>Đã hủy</color>: Đã bị hủy bỏ<br/><br/><b>Ràng buộc:</b><br/>• <b><color=Red>Bắt buộc chọn</color></b> (có dấu * đỏ)<br/>• Không được để trống<br/><br/><b>Validation:</b><br/>• Kiểm tra rỗng khi validating<br/>• Hiển thị lỗi: ""Trạng thái kiểm kho không được để trống""<br/><br/><color=Gray>Lưu ý:</color> Trạng thái kiểm kho sẽ được lưu vào database khi lưu phiếu kiểm kho."
                );
            }
        }

        /// <summary>
        /// Thiết lập SuperToolTip cho các SearchLookUpEdit controls
        /// </summary>
        private void SetupSearchLookupEditSuperTips()
        {
            // SuperTip cho Kho kiểm
            if (WarehouseNameSearchLookupEdit != null)
            {
                SuperToolTipHelper.SetBaseEditSuperTip(
                    WarehouseNameSearchLookupEdit,
                    title: @"<b><color=DarkBlue>🏢 Kho kiểm</color></b>",
                    content: @"Chọn kho kiểm từ danh sách chi nhánh (Company Branch) đang hoạt động.<br/><br/><b>Chức năng:</b><br/>• Chọn kho cần kiểm<br/>• Hiển thị thông tin kho dạng HTML (mã, tên)<br/>• Tự động cập nhật WarehouseId, CompanyBranchId vào DTO<br/><br/><b>Ràng buộc:</b><br/>• <b><color=Red>Bắt buộc chọn</color></b> (có dấu * đỏ)<br/>• Không được để trống<br/>• Chỉ hiển thị các chi nhánh đang hoạt động (IsActive = true)<br/><br/><b>Data Source:</b><br/>• Load từ CompanyBranchBll.GetAll()<br/>• Filter chỉ lấy các chi nhánh đang hoạt động<br/>• Sắp xếp theo tên chi nhánh<br/><br/><b>Validation:</b><br/>• Kiểm tra rỗng khi validating<br/>• Hiển thị lỗi: ""Kho kiểm không được để trống""<br/>• Hiển thị lỗi qua ErrorProvider nếu không hợp lệ<br/><br/><color=Gray>Lưu ý:</color> Kho kiểm sẽ được lưu vào database khi lưu phiếu kiểm kho."
                );
            }
        }

        /// <summary>
        /// Thiết lập SuperToolTip cho các MemoEdit controls
        /// </summary>
        private void SetupMemoEditSuperTips()
        {
            // SuperTip cho Ghi chú
            if (NotesTextEdit != null)
            {
                SuperToolTipHelper.SetBaseEditSuperTip(
                    NotesTextEdit,
                    title: @"<b><color=DarkBlue>📝 Ghi chú</color></b>",
                    content: @"Nhập ghi chú hoặc mô tả bổ sung cho phiếu kiểm kho.<br/><br/><b>Chức năng:</b><br/>• Lưu thông tin bổ sung về phiếu kiểm kho<br/>• Ghi chú về lý do kiểm kho, điều kiện kiểm, v.v.<br/>• Hỗ trợ nhiều dòng văn bản<br/><br/><b>Ràng buộc:</b><br/>• <color=Green>Không bắt buộc</color> (có thể để trống)<br/>• Không giới hạn độ dài<br/><br/><color=Gray>Lưu ý:</color> Ghi chú sẽ được lưu vào database khi lưu phiếu kiểm kho."
                );
            }

            // SuperTip cho Lý do
            if (ReasonTextEdit != null)
            {
                SuperToolTipHelper.SetBaseEditSuperTip(
                    ReasonTextEdit,
                    title: @"<b><color=DarkBlue>📋 Lý do</color></b>",
                    content: @"Nhập lý do kiểm kho.<br/><br/><b>Chức năng:</b><br/>• Ghi nhận lý do thực hiện kiểm kho<br/>• Hỗ trợ tra cứu và theo dõi<br/>• Hỗ trợ nhiều dòng văn bản<br/><br/><b>Ràng buộc:</b><br/>• <color=Green>Không bắt buộc</color> (có thể để trống)<br/>• Không giới hạn độ dài<br/><br/><color=Gray>Lưu ý:</color> Lý do sẽ được lưu vào database khi lưu phiếu kiểm kho."
                );
            }
        }

        /// <summary>
        /// Thiết lập SuperToolTip cho các ToggleSwitch controls
        /// </summary>
        private void SetupToggleSwitchSuperTips()
        {
            // SuperTip cho Khóa phiếu
            if (IsLockedToggleSwitch != null)
            {
                SuperToolTipHelper.SetBaseEditSuperTip(
                    IsLockedToggleSwitch,
                    title: @"<b><color=DarkBlue>🔒 Khóa phiếu</color></b>",
                    content: @"Bật/tắt khóa phiếu kiểm kho.<br/><br/><b>Chức năng:</b><br/>• Khóa phiếu để không cho chỉnh sửa<br/>• Bảo vệ dữ liệu đã được xác nhận<br/>• Ghi nhận thời gian và người khóa<br/><br/><b>Trạng thái:</b><br/>• <color=Blue>Chưa khóa</color>: Có thể chỉnh sửa<br/>• <color=Red>Đã khóa</color>: Không thể chỉnh sửa<br/><br/><b>Ràng buộc:</b><br/>• <color=Green>Không bắt buộc</color> (có thể để trống)<br/>• Mặc định: Chưa khóa<br/><br/><color=Gray>Lưu ý:</color> Khi khóa phiếu, hệ thống sẽ ghi nhận thời gian và người khóa."
                );
            }
        }

        #endregion

        #region ========== HELPER METHODS ==========

        /// <summary>
        /// Hiển thị lỗi từ Exception
        /// </summary>
        private void ShowError(Exception ex, string message)
        {
            try
            {
                // Tìm parent form để làm owner cho MsgBox
                var parentForm = FindForm();
                
                // Sử dụng MsgBox.ShowException hoặc ShowError với thông báo chi tiết
                if (ex != null)
                {
                    MsgBox.ShowException(ex, message, parentForm);
                }
                else
                {
                    MsgBox.ShowError(message, "Lỗi", parentForm);
                }
            }
            catch
            {
                // Fallback nếu có lỗi khi hiển thị MsgBox
                System.Diagnostics.Debug.WriteLine($"Lỗi: {message}: {ex?.Message}");
            }
        }

        /// <summary>
        /// Hiển thị lỗi
        /// </summary>
        private void ShowError(string message)
        {
            try
            {
                // Tìm parent form để làm owner cho MsgBox
                var parentForm = FindForm();
                
                // Sử dụng MsgBox.ShowError
                MsgBox.ShowError(message, "Lỗi", parentForm);
            }
            catch
            {
                // Fallback nếu có lỗi khi hiển thị MsgBox
                System.Diagnostics.Debug.WriteLine($"Lỗi: {message}");
            }
        }

        #endregion
    }
}