<?xml version="1.0" encoding="utf-8"?><Database Name="VnsErp2025Final" Class="VnsErp2025DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=115.75.187.3,3306;Initial Catalog=VnsErp2025Final;Persist Security Info=True;User ID=vns;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="Dal.Properties.Settings" SettingsPropertyName="VnsErp2025FinalConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ApplicationUser" Member="ApplicationUsers">
    <Type Name="ApplicationUser">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HashPassword" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ApplicationUser_InventoryBalance" Member="InventoryBalances" ThisKey="Id" OtherKey="ApprovedBy" Type="InventoryBalance" />
      <Association Name="ApplicationUser_InventoryBalance1" Member="InventoryBalances1" ThisKey="Id" OtherKey="CreateBy" Type="InventoryBalance" />
      <Association Name="ApplicationUser_InventoryBalance2" Member="InventoryBalances2" ThisKey="Id" OtherKey="DeletedBy" Type="InventoryBalance" />
      <Association Name="ApplicationUser_InventoryBalance3" Member="InventoryBalances3" ThisKey="Id" OtherKey="LockedBy" Type="InventoryBalance" />
      <Association Name="ApplicationUser_InventoryBalance4" Member="InventoryBalances4" ThisKey="Id" OtherKey="ModifiedBy" Type="InventoryBalance" />
      <Association Name="ApplicationUser_InventoryBalance5" Member="InventoryBalances5" ThisKey="Id" OtherKey="VerifiedBy" Type="InventoryBalance" />
    </Type>
  </Table>
  <Table Name="dbo.Warranty" Member="Warranties">
    <Type Name="Warranty">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StockInOutDetailId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="WarrantyType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WarrantyFrom" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MonthOfWarranty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WarrantyUntil" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WarrantyStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UniqueProductInfo" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Warranty_Device" Member="Devices" ThisKey="Id" OtherKey="WarrantyId" Type="Device" />
      <Association Name="StockInOutDetail_Warranty" Member="StockInOutDetail" ThisKey="StockInOutDetailId" OtherKey="Id" Type="StockInOutDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Attribute" Member="Attributes">
    <Type Name="Attribute">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Attribute_AttributeValue" Member="AttributeValues" ThisKey="Id" OtherKey="AttributeId" Type="AttributeValue" />
      <Association Name="Attribute_VariantAttribute" Member="VariantAttributes" ThisKey="Id" OtherKey="AttributeId" Type="VariantAttribute" />
    </Type>
  </Table>
  <Table Name="dbo.AttributeValue" Member="AttributeValues">
    <Type Name="AttributeValue">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AttributeId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="AttributeValue_VariantAttribute" Member="VariantAttributes" ThisKey="Id" OtherKey="AttributeValueId" Type="VariantAttribute" />
      <Association Name="Attribute_AttributeValue" Member="Attribute" ThisKey="AttributeId" OtherKey="Id" Type="Attribute" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BusinessPartner" Member="BusinessPartners">
    <Type Name="BusinessPartner">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PartnerCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PartnerName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PartnerType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ContactPosition" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreditLimit" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PaymentTerm" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="BusinessPartner_BusinessPartner_BusinessPartnerCategory" Member="BusinessPartner_BusinessPartnerCategories" ThisKey="Id" OtherKey="PartnerId" Type="BusinessPartner_BusinessPartnerCategory" />
      <Association Name="BusinessPartner_BusinessPartnerSite" Member="BusinessPartnerSites" ThisKey="Id" OtherKey="PartnerId" Type="BusinessPartnerSite" />
      <Association Name="BusinessPartner_StockInOutDocument" Member="StockInOutDocuments" ThisKey="Id" OtherKey="BusinessPartnerId" Type="StockInOutDocument" />
    </Type>
  </Table>
  <Table Name="dbo.BusinessPartner_BusinessPartnerCategory" Member="BusinessPartner_BusinessPartnerCategories">
    <Type Name="BusinessPartner_BusinessPartnerCategory">
      <Column Name="PartnerId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="BusinessPartner_BusinessPartner_BusinessPartnerCategory" Member="BusinessPartner" ThisKey="PartnerId" OtherKey="Id" Type="BusinessPartner" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="BusinessPartnerCategory_BusinessPartner_BusinessPartnerCategory" Member="BusinessPartnerCategory" ThisKey="CategoryId" OtherKey="Id" Type="BusinessPartnerCategory" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BusinessPartnerCategory" Member="BusinessPartnerCategories">
    <Type Name="BusinessPartnerCategory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="BusinessPartnerCategory_BusinessPartner_BusinessPartnerCategory" Member="BusinessPartner_BusinessPartnerCategories" ThisKey="Id" OtherKey="CategoryId" Type="BusinessPartner_BusinessPartnerCategory" />
      <Association Name="BusinessPartnerCategory_BusinessPartnerCategory" Member="BusinessPartnerCategories" ThisKey="Id" OtherKey="ParentId" Type="BusinessPartnerCategory" />
      <Association Name="BusinessPartnerCategory_BusinessPartnerCategory" Member="BusinessPartnerCategory1" ThisKey="ParentId" OtherKey="Id" Type="BusinessPartnerCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BusinessPartnerContact" Member="BusinessPartnerContacts">
    <Type Name="BusinessPartnerContact">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SiteId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsPrimary" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="BusinessPartnerSite_BusinessPartnerContact" Member="BusinessPartnerSite" ThisKey="SiteId" OtherKey="Id" Type="BusinessPartnerSite" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BusinessPartnerSite" Member="BusinessPartnerSites">
    <Type Name="BusinessPartnerSite">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PartnerId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="SiteCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="BusinessPartnerSite_BusinessPartnerContact" Member="BusinessPartnerContacts" ThisKey="Id" OtherKey="SiteId" Type="BusinessPartnerContact" />
      <Association Name="BusinessPartnerSite_StockInOutMaster" Member="StockInOutMasters" ThisKey="Id" OtherKey="PartnerSiteId" Type="StockInOutMaster" />
      <Association Name="BusinessPartner_BusinessPartnerSite" Member="BusinessPartner" ThisKey="PartnerId" OtherKey="Id" Type="BusinessPartner" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LogoFileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LogoRelativePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LogoFullPath" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="LogoStorageType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LogoFileSize" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="LogoChecksum" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Association Name="Company_CompanyBranch" Member="CompanyBranches" ThisKey="Id" OtherKey="CompanyId" Type="CompanyBranch" />
      <Association Name="Company_Department" Member="Departments" ThisKey="Id" OtherKey="CompanyId" Type="Department" />
      <Association Name="Company_Device" Member="Devices" ThisKey="Id" OtherKey="CompanyId" Type="Device" />
      <Association Name="Company_Employee" Member="Employees" ThisKey="Id" OtherKey="CompanyId" Type="Employee" />
      <Association Name="Company_Position" Member="Positions" ThisKey="Id" OtherKey="CompanyId" Type="Position" />
    </Type>
  </Table>
  <Table Name="dbo.CompanyBranch" Member="CompanyBranches">
    <Type Name="CompanyBranch">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BranchCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ManagerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CompanyBranch_Department" Member="Departments" ThisKey="Id" OtherKey="BranchId" Type="Department" />
      <Association Name="CompanyBranch_Device" Member="Devices" ThisKey="Id" OtherKey="BranchId" Type="Device" />
      <Association Name="CompanyBranch_DeviceTransfer" Member="DeviceTransfers" ThisKey="Id" OtherKey="FromBranchId" Type="DeviceTransfer" />
      <Association Name="CompanyBranch_DeviceTransfer1" Member="DeviceTransfers1" ThisKey="Id" OtherKey="ToBranchId" Type="DeviceTransfer" />
      <Association Name="CompanyBranch_Employee" Member="Employees" ThisKey="Id" OtherKey="BranchId" Type="Employee" />
      <Association Name="CompanyBranch_InventoryBalance" Member="InventoryBalances" ThisKey="Id" OtherKey="WarehouseId" Type="InventoryBalance" />
      <Association Name="CompanyBranch_StockInOutMaster" Member="StockInOutMasters" ThisKey="Id" OtherKey="WarehouseId" Type="StockInOutMaster" />
      <Association Name="Company_CompanyBranch" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DepartmentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Department_Department" Member="Departments" ThisKey="Id" OtherKey="ParentId" Type="Department" />
      <Association Name="Department_Device" Member="Devices" ThisKey="Id" OtherKey="DepartmentId" Type="Device" />
      <Association Name="Department_DeviceTransfer" Member="DeviceTransfers" ThisKey="Id" OtherKey="FromDepartmentId" Type="DeviceTransfer" />
      <Association Name="Department_DeviceTransfer1" Member="DeviceTransfers1" ThisKey="Id" OtherKey="ToDepartmentId" Type="DeviceTransfer" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="Id" OtherKey="DepartmentId" Type="Employee" />
      <Association Name="CompanyBranch_Department" Member="CompanyBranch" ThisKey="BranchId" OtherKey="Id" Type="CompanyBranch" IsForeignKey="true" />
      <Association Name="Company_Department" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Department_Department" Member="Department1" ThisKey="ParentId" OtherKey="Id" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Device" Member="Devices">
    <Type Name="Device">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductVariantId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StockInOutDetailId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="WarrantyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MACAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IMEI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AssetTag" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseKey" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HostName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AssignedEmployeeId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeviceType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InstallationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastMaintenanceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NextMaintenanceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Specifications" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Configuration" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Device_DeviceHistory" Member="DeviceHistories" ThisKey="Id" OtherKey="DeviceId" Type="DeviceHistory" />
      <Association Name="Device_DeviceTransfer" Member="DeviceTransfers" ThisKey="Id" OtherKey="DeviceId" Type="DeviceTransfer" />
      <Association Name="Company_Device" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" />
      <Association Name="CompanyBranch_Device" Member="CompanyBranch" ThisKey="BranchId" OtherKey="Id" Type="CompanyBranch" IsForeignKey="true" />
      <Association Name="Department_Device" Member="Department" ThisKey="DepartmentId" OtherKey="Id" Type="Department" IsForeignKey="true" />
      <Association Name="Warranty_Device" Member="Warranty" ThisKey="WarrantyId" OtherKey="Id" Type="Warranty" IsForeignKey="true" />
      <Association Name="Employee_Device" Member="Employee" ThisKey="AssignedEmployeeId" OtherKey="Id" Type="Employee" IsForeignKey="true" />
      <Association Name="ProductVariant_Device" Member="ProductVariant" ThisKey="ProductVariantId" OtherKey="Id" Type="ProductVariant" IsForeignKey="true" />
      <Association Name="StockInOutDetail_Device" Member="StockInOutDetail" ThisKey="StockInOutDetailId" OtherKey="Id" Type="StockInOutDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceHistory" Member="DeviceHistories">
    <Type Name="DeviceHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeviceId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ChangeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChangeDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ChangedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OldValue" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NewValue" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="Device_DeviceHistory" Member="Device" ThisKey="DeviceId" OtherKey="Id" Type="Device" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceTransfer" Member="DeviceTransfers">
    <Type Name="DeviceTransfer">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeviceId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TransferDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FromBranchId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FromDepartmentId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FromEmployeeId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FromLocation" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ToBranchId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ToDepartmentId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ToEmployeeId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ToLocation" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TransferReason" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TransferBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Device_DeviceTransfer" Member="Device" ThisKey="DeviceId" OtherKey="Id" Type="Device" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="CompanyBranch_DeviceTransfer" Member="CompanyBranch" ThisKey="FromBranchId" OtherKey="Id" Type="CompanyBranch" IsForeignKey="true" />
      <Association Name="Department_DeviceTransfer" Member="Department" ThisKey="FromDepartmentId" OtherKey="Id" Type="Department" IsForeignKey="true" />
      <Association Name="CompanyBranch_DeviceTransfer1" Member="CompanyBranch1" ThisKey="ToBranchId" OtherKey="Id" Type="CompanyBranch" IsForeignKey="true" />
      <Association Name="Department_DeviceTransfer1" Member="Department1" ThisKey="ToDepartmentId" OtherKey="Id" Type="Department" IsForeignKey="true" />
      <Association Name="Employee_DeviceTransfer" Member="Employee" ThisKey="FromEmployeeId" OtherKey="Id" Type="Employee" IsForeignKey="true" />
      <Association Name="Employee_DeviceTransfer1" Member="Employee1" ThisKey="ToEmployeeId" OtherKey="Id" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PositionId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HireDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ResignDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AvatarPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Device" Member="Devices" ThisKey="Id" OtherKey="AssignedEmployeeId" Type="Device" />
      <Association Name="Employee_DeviceTransfer" Member="DeviceTransfers" ThisKey="Id" OtherKey="FromEmployeeId" Type="DeviceTransfer" />
      <Association Name="Employee_DeviceTransfer1" Member="DeviceTransfers1" ThisKey="Id" OtherKey="ToEmployeeId" Type="DeviceTransfer" />
      <Association Name="CompanyBranch_Employee" Member="CompanyBranch" ThisKey="BranchId" OtherKey="Id" Type="CompanyBranch" IsForeignKey="true" />
      <Association Name="Company_Employee" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DepartmentId" OtherKey="Id" Type="Department" IsForeignKey="true" />
      <Association Name="Position_Employee" Member="Position" ThisKey="PositionId" OtherKey="Id" Type="Position" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InventoryBalance" Member="InventoryBalances">
    <Type Name="InventoryBalance">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WarehouseId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProductVariantId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PeriodYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PeriodMonth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OpeningBalance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalInQty" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalOutQty" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ClosingBalance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="OpeningValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalInValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalOutValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ClosingValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalInVatAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalOutVatAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalInAmountIncludedVat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalOutAmountIncludedVat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsLocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LockReason" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsVerified" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VerifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VerifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="VerificationNotes" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ApprovalNotes" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="ApplicationUser_InventoryBalance" Member="ApplicationUser" ThisKey="ApprovedBy" OtherKey="Id" Type="ApplicationUser" IsForeignKey="true" />
      <Association Name="CompanyBranch_InventoryBalance" Member="CompanyBranch" ThisKey="WarehouseId" OtherKey="Id" Type="CompanyBranch" IsForeignKey="true" />
      <Association Name="ApplicationUser_InventoryBalance1" Member="ApplicationUser1" ThisKey="CreateBy" OtherKey="Id" Type="ApplicationUser" IsForeignKey="true" />
      <Association Name="ApplicationUser_InventoryBalance2" Member="ApplicationUser2" ThisKey="DeletedBy" OtherKey="Id" Type="ApplicationUser" IsForeignKey="true" />
      <Association Name="ApplicationUser_InventoryBalance3" Member="ApplicationUser3" ThisKey="LockedBy" OtherKey="Id" Type="ApplicationUser" IsForeignKey="true" />
      <Association Name="ApplicationUser_InventoryBalance4" Member="ApplicationUser4" ThisKey="ModifiedBy" OtherKey="Id" Type="ApplicationUser" IsForeignKey="true" />
      <Association Name="ApplicationUser_InventoryBalance5" Member="ApplicationUser5" ThisKey="VerifiedBy" OtherKey="Id" Type="ApplicationUser" IsForeignKey="true" />
      <Association Name="ProductVariant_InventoryBalance" Member="ProductVariant" ThisKey="ProductVariantId" OtherKey="Id" Type="ProductVariant" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Position" Member="Positions">
    <Type Name="Position">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PositionCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PositionName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsManagerLevel" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Position_Employee" Member="Employees" ThisKey="Id" OtherKey="PositionId" Type="Employee" />
      <Association Name="Company_Position" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductImage" Member="ProductImages">
    <Type Name="ProductImage">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="VariantId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsPrimary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ImageData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ImageType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ImageSize" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ImageWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Caption" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AltText" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RelativePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FullPath" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NASShareName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StorageType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StorageProvider" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileExtension" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MimeType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Checksum" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="HasThumbnail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThumbnailPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ThumbnailFileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccessUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="FileExists" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastVerified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MigrationStatus" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="ProductService_ProductImage" Member="ProductService" ThisKey="ProductId" OtherKey="Id" Type="ProductService" IsForeignKey="true" />
      <Association Name="ProductVariant_ProductImage" Member="ProductVariant" ThisKey="VariantId" OtherKey="Id" Type="ProductVariant" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductService" Member="ProductServices">
    <Type Name="ProductService">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsService" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ThumbnailFileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ThumbnailRelativePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ThumbnailFullPath" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ThumbnailStorageType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ThumbnailFileSize" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ThumbnailChecksum" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Association Name="ProductService_ProductImage" Member="ProductImages" ThisKey="Id" OtherKey="ProductId" Type="ProductImage" />
      <Association Name="ProductService_ProductVariant" Member="ProductVariants" ThisKey="Id" OtherKey="ProductId" Type="ProductVariant" />
      <Association Name="ProductServiceCategory_ProductService" Member="ProductServiceCategory" ThisKey="CategoryId" OtherKey="Id" Type="ProductServiceCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductServiceCategory" Member="ProductServiceCategories">
    <Type Name="ProductServiceCategory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CategoryCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ProductServiceCategory_ProductService" Member="ProductServices" ThisKey="Id" OtherKey="CategoryId" Type="ProductService" />
      <Association Name="ProductServiceCategory_ProductServiceCategory" Member="ProductServiceCategories" ThisKey="Id" OtherKey="ParentId" Type="ProductServiceCategory" />
      <Association Name="ProductServiceCategory_ProductServiceCategory" Member="ProductServiceCategory1" ThisKey="ParentId" OtherKey="Id" Type="ProductServiceCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductVariant" Member="ProductVariants">
    <Type Name="ProductVariant">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VariantCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UnitId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="VariantFullName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ThumbnailFileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ThumbnailRelativePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ThumbnailFullPath" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ThumbnailStorageType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ThumbnailFileSize" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ThumbnailChecksum" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Association Name="ProductVariant_Device" Member="Devices" ThisKey="Id" OtherKey="ProductVariantId" Type="Device" />
      <Association Name="ProductVariant_InventoryBalance" Member="InventoryBalances" ThisKey="Id" OtherKey="ProductVariantId" Type="InventoryBalance" />
      <Association Name="ProductVariant_ProductImage" Member="ProductImages" ThisKey="Id" OtherKey="VariantId" Type="ProductImage" />
      <Association Name="ProductVariant_StockInOutDetail" Member="StockInOutDetails" ThisKey="Id" OtherKey="ProductVariantId" Type="StockInOutDetail" />
      <Association Name="ProductVariant_VariantAttribute" Member="VariantAttributes" ThisKey="Id" OtherKey="VariantId" Type="VariantAttribute" />
      <Association Name="ProductService_ProductVariant" Member="ProductService" ThisKey="ProductId" OtherKey="Id" Type="ProductService" IsForeignKey="true" />
      <Association Name="UnitOfMeasure_ProductVariant" Member="UnitOfMeasure" ThisKey="UnitId" OtherKey="Id" Type="UnitOfMeasure" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StockInOutDetail" Member="StockInOutDetails">
    <Type Name="StockInOutDetail">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StockInOutMasterId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProductVariantId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StockInQty" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="StockOutQty" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Vat" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="VatAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmountIncludedVat" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="StockInOutDetail_Warranty" Member="Warranties" ThisKey="Id" OtherKey="StockInOutDetailId" Type="Warranty" />
      <Association Name="StockInOutDetail_Device" Member="Devices" ThisKey="Id" OtherKey="StockInOutDetailId" Type="Device" />
      <Association Name="ProductVariant_StockInOutDetail" Member="ProductVariant" ThisKey="ProductVariantId" OtherKey="Id" Type="ProductVariant" IsForeignKey="true" />
      <Association Name="StockInOutMaster_StockInOutDetail" Member="StockInOutMaster" ThisKey="StockInOutMasterId" OtherKey="Id" Type="StockInOutMaster" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StockInOutDocument" Member="StockInOutDocuments">
    <Type Name="StockInOutDocument">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StockInOutMasterId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="BusinessPartnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PurchaseOrderId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RelatedEntityType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RelatedEntityId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DocumentType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentCategory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentSubType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RelativePath" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FullPath" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NASShareName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StorageType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StorageProvider" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileExtension" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MimeType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FileSize" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Checksum" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="FileVersion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentNumber" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DocumentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsConfidential" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccessUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FileExists" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastVerified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VerifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="VerifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MigrationStatus" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HasThumbnail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThumbnailPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ThumbnailFileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="BusinessPartner_StockInOutDocument" Member="BusinessPartner" ThisKey="BusinessPartnerId" OtherKey="Id" Type="BusinessPartner" IsForeignKey="true" />
      <Association Name="StockInOutMaster_StockInOutDocument" Member="StockInOutMaster" ThisKey="StockInOutMasterId" OtherKey="Id" Type="StockInOutMaster" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StockInOutImage" Member="StockInOutImages">
    <Type Name="StockInOutImage">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StockInOutMasterId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ImageData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RelativePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FullPath" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="StorageType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FileSize" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FileExtension" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MimeType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Checksum" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="FileExists" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastVerified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MigrationStatus" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="StockInOutMaster_StockInOutImage" Member="StockInOutMaster" ThisKey="StockInOutMasterId" OtherKey="Id" Type="StockInOutMaster" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StockInOutMaster" Member="StockInOutMasters">
    <Type Name="StockInOutMaster">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StockInOutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VocherNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StockInOutType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VoucherStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WarehouseId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseOrderId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PartnerSiteId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TotalQuantity" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalVat" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmountIncludedVat" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NguoiNhanHang" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NguoiGiaoHang" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="StockInOutMaster_StockInOutDetail" Member="StockInOutDetails" ThisKey="Id" OtherKey="StockInOutMasterId" Type="StockInOutDetail" />
      <Association Name="StockInOutMaster_StockInOutDocument" Member="StockInOutDocuments" ThisKey="Id" OtherKey="StockInOutMasterId" Type="StockInOutDocument" />
      <Association Name="StockInOutMaster_StockInOutImage" Member="StockInOutImages" ThisKey="Id" OtherKey="StockInOutMasterId" Type="StockInOutImage" />
      <Association Name="BusinessPartnerSite_StockInOutMaster" Member="BusinessPartnerSite" ThisKey="PartnerSiteId" OtherKey="Id" Type="BusinessPartnerSite" IsForeignKey="true" />
      <Association Name="CompanyBranch_StockInOutMaster" Member="CompanyBranch" ThisKey="WarehouseId" OtherKey="Id" Type="CompanyBranch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UnitOfMeasure" Member="UnitOfMeasures">
    <Type Name="UnitOfMeasure">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UnitOfMeasure_ProductVariant" Member="ProductVariants" ThisKey="Id" OtherKey="UnitId" Type="ProductVariant" />
    </Type>
  </Table>
  <Table Name="dbo.VariantAttribute" Member="VariantAttributes">
    <Type Name="VariantAttribute">
      <Column Name="VariantId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AttributeId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AttributeValueId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Attribute_VariantAttribute" Member="Attribute" ThisKey="AttributeId" OtherKey="Id" Type="Attribute" IsForeignKey="true" />
      <Association Name="AttributeValue_VariantAttribute" Member="AttributeValue" ThisKey="AttributeValueId" OtherKey="Id" Type="AttributeValue" IsForeignKey="true" />
      <Association Name="ProductVariant_VariantAttribute" Member="ProductVariant" ThisKey="VariantId" OtherKey="Id" Type="ProductVariant" IsForeignKey="true" />
    </Type>
  </Table>
</Database>