//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.199;Initial Catalog=VnsErp2025Final;Persist Security Info=T" +
            "rue;User ID=sa;Password=VNS@#2023;TrustServerCertificate=True")]
        public string VnsErp2025FinalConnectionString {
            get {
                return ((string)(this["VnsErp2025FinalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=115.75.187.3,3306;Initial Catalog=VnsErp2025Final;Persist Security In" +
            "fo=True;User ID=vns;TrustServerCertificate=True")]
        public string VnsErp2025FinalConnectionString1 {
            get {
                return ((string)(this["VnsErp2025FinalConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=115.75.187.3,3306;Initial Catalog=VnsErp2025Final;Persist Security In" +
            "fo=True;User ID=vns;Password=VNS@#2025;Encrypt=True;TrustServerCertificate=True")]
        public string VnsErp2025FinalConnectionString2 {
            get {
                return ((string)(this["VnsErp2025FinalConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=115.75.187.3,3306;Initial Catalog=VnsErp2025Final;Persist Security In" +
            "fo=True;User ID=vns;Encrypt=True;TrustServerCertificate=True")]
        public string VnsErp2025FinalConnectionString3 {
            get {
                return ((string)(this["VnsErp2025FinalConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=115.75.187.3,3306;Initial Catalog=VnsErp2025Final;Persist Security In" +
            "fo=True;User ID=vns;Encrypt=True;TrustServerCertificate=True")]
        public string VnsErp2025FinalConnectionString4 {
            get {
                return ((string)(this["VnsErp2025FinalConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=115.75.187.3,3306;Initial Catalog=VnsErp2025Final;Persist Security In" +
            "fo=True;User ID=vns;Encrypt=True;TrustServerCertificate=True")]
        public string VnsErp2025FinalConnectionString5 {
            get {
                return ((string)(this["VnsErp2025FinalConnectionString5"]));
            }
        }
    }
}
